FROM php:8.4.17-apache
RUN docker-php-ext-install pdo pdo_mysql mysqli
WORKDIR /var/www/html/
COPY test/ ./test/
RUN chown -R www-data:www-data /var/www
EXPOSE 80
#podman build -t localhost/webserver:v1 .
#podman run -d -p 8080:80 --network=podman --name webserver localhost/webserver:v1
